let foodLinks = 
{
  Pizza: [ 'pizza.jpg', 'wikipedia.org/wiki/Pizza' ],
  'Full English Breakfast': [ 'full_english_breakfast.jpg', 'wikipedia.org/wiki/Full_breakfast' ],
  Risotto: [ 'risotto.jpg', 'wikipedia.org/wiki/Risotto' ],
  Katsudon: [ 'katsudon.jpg', 'wikipedia.org/wiki/Katsudon' ],
  Bibimbap: [ 'bibimbap.jpg', 'wikipedia.org/wiki/Bibimbap' ],
  'Bak Chor Mee': [ 'bak_chor_mee.jpg', 'wikipedia.org/wiki/Mee_pok' ],
  'Hainanese Chicken Rice': [
    'hainanese_chicken_rice.jpg',
    'wikipedia.org/wiki/Hainanese_chicken_rice'
  ],
  'Ginseng Chicken Soup': [ 'ginseng_chicken_soup.jpg', 'wikipedia.org/wiki/Samgye-tang' ],
  Bingsu: [ 'bingsu.jpg', 'wikipedia.org/wiki/Bingsu' ],
  'Tortang Talong': [ 'tortang_talong.jpg', 'wikipedia.org/wiki/Tortang_talong' ],
  'Caesar Salad': [ 'caesar_salad.jpg', 'wikipedia.org/wiki/Caesar_salad' ],
  Ceviche: [ 'ceviche.jfif', 'wikipedia.org/wiki/Ceviche' ],
  'Aush Reshteh': [ 'aush_reshteh.jpg', 'wikipedia.org/wiki/Aush_reshteh' ],
  Aushak: [ 'aushak.jpg', 'wikipedia.org/wiki/Aushak' ],
  Bolani: [ 'bolani.jpg', 'wikipedia.org/wiki/Bolani' ],
  'Chapli Kabab': [ 'chapli_kabab.jfif', 'wikipedia.org/wiki/Chapli_kebab' ],
  Fesenjan: [ 'fesenjan.jpg', 'wikipedia.org/wiki/Fesenjān' ],
  Kesme: [ 'kesme.jpg', 'wikipedia.org/wiki/Kesme' ],
  Gheimeh: [ 'gheimeh.jpg', 'wikipedia.org/wiki/Gheimeh' ],
  Baklava: [ 'baklava.png', 'wikipedia.org/wiki/Baklava' ],
  Knafeh: [ 'knafeh.jpg', 'wikipedia.org/wiki/Knafeh' ],
  'Baba Ghanoush': [ 'baba_ghanoush.jfif', 'wikipedia.org/wiki/Baba_ghanoush' ],
  Balaleet: [ 'balaleet.jpg', 'wikipedia.org/wiki/Balaleet' ],
  Chakhchoukha: [ 'chakhchoukha.jpg', 'wikipedia.org/wiki/Chakhchoukha' ],
  Chebakia: [ 'chebakia.jpg', 'wikipedia.org/wiki/Chebakia' ],
  Churros: [ 'churros.jpg', 'wikipedia.org/wiki/Churro' ],
  Frittata: [ 'frittata.jpg', 'wikipedia.org/wiki/Frittata' ],
  'Quiche Lorraine': [ 'quiche_lorraine.jpg', 'wikipedia.org/wiki/Quiche_Lorraine' ],
  Faloodeh: [ 'faloodeh.jpg', 'wikipedia.org/wiki/Faloodeh' ],
  Fatayer: [ 'fatayer.jpg', 'wikipedia.org/wiki/Fatayer' ],
  'Turkish Delight': [ 'turkish_delight.jpg', 'wikipedia.org/wiki/Turkish_delight' ],
  'Australian Meat Pie': [
    'australian_meat_pie.jpg',
    'wikipedia.org/wiki/Meat_pie_(Australia_and_New_Zealand)'
  ],
  'Egg Drop Soup': [ 'egg_drop_soup.jpg', 'wikipedia.org/wiki/Egg_drop_soup' ],
  Eiernockerl: [ 'eiernockerl.jpg', 'wikipedia.org/wiki/Eiernockerl' ],
  Gnocchi: [ 'gnocchi.jpg', 'wikipedia.org/wiki/Gnocchi' ],
  'Frankenburger Bratknodel': [
    'frankenburger_bratknodel.jpg',
    'wikipedia.org/wiki/Frankenburger_Bratknödel'
  ],
  Goulash: [ 'goulash.jpg', 'wikipedia.org/wiki/Goulash' ],
  Tafelspitz: [ 'tafelspitz.jpg', 'wikipedia.org/wiki/Tafelspitz' ],
  'Apple Strudel': [ 'apple_strudel.jpg', 'wikipedia.org/wiki/Apple_strudel' ],
  'Apple Pie': [ 'apple_pie.jpg', 'wikipedia.org/wiki/Apple_pie' ],
  Kaiserschmarrn: [ 'kaiserschmarrn.jpg', 'wikipedia.org/wiki/Kaiserschmarrn' ],
  Germknodel: [ 'germknodel.jpg', 'wikipedia.org/wiki/Germknödel' ],
  Kasespatzle: [ 'kasespatzle.jpg', 'wikipedia.org/wiki/Käsespätzle' ],
  'Wiener Schnitzel': [ 'wiener_schnitzel.jpg', 'wikipedia.org/wiki/Wiener_schnitzel' ],
  Mezzelune: [ 'mezzelune.jfif', 'wikipedia.org/wiki/Schlutzkrapfen' ],
  'Kuku Sabzi': [ 'kuku_sabzi.jpg', 'wikipedia.org/wiki/Kuku_(food)' ],
  Dovga: [ 'dovga.jfif', 'wikipedia.org/wiki/Dovga' ],
  Khachapuri: [ 'khachapuri.jpg', 'wikipedia.org/wiki/Khachapuri' ],
  Ajapsandali: [ 'ajapsandali.jpg', 'wikipedia.org/wiki/Ajapsandali' ],
  Ghapama: [ 'ghapama.jfif', 'wikipedia.org/wiki/Ghapama' ],
  'Bangers And Mash': [ 'bangers_and_mash.jpg', 'wikipedia.org/wiki/Bangers_and_mash' ],
  'Cauliflower Cheese': [ 'cauliflower_cheese.jpg', 'wikipedia.org/wiki/Cauliflower_cheese' ],
  'Chicken Tikka Masala': [
    'chicken_tikka_masala.jpg',
    'wikipedia.org/wiki/Chicken_tikka_masala'
  ],
  'Chicken Tikka': [ 'chicken_tikka.jpg', 'wikipedia.org/wiki/Chicken_tikka' ],
  'Butter Chicken': [ 'butter_chicken.jpg', 'wikipedia.org/wiki/Butter_chicken' ],
  'Coronation Chicken': [ 'coronation_chicken.jpg', 'wikipedia.org/wiki/Coronation_chicken' ],
  'Devilled Kidneys': [ 'devilled_kidneys.jpg', 'wikipedia.org/wiki/Devilled_kidneys' ],
  'Deviled Eggs': [ 'deviled_eggs.jpg', 'wikipedia.org/wiki/Deviled_egg' ],
  'Eton Mess': [ 'eton_mess.jpg', 'wikipedia.org/wiki/Eton_mess' ],
  'Fish And Chips': [ 'fish_and_chips', 'wikipedia.org/wiki/Fish_and_chips' ],
  'Platinum Pudding': [ 'platinum_pudding.jpg', 'wikipedia.org/wiki/Platinum_Pudding' ],
  'Potato Salad': [ 'potato_salad.jpg', 'wikipedia.org/wiki/Potato_salad' ],
  'Black Pudding': [ 'black.pudding.jpg', 'wikipedia.org/wiki/Black_pudding' ],
  'Kitchener Bun': [ 'kitchener_bun.jpg', 'wikipedia.org/wiki/Kitchener_bun' ],
  Palmier: [ 'palmier.jpg', 'wikipedia.org/wiki/Palmier' ],
  Empanada: [ 'empanada.jfif', 'wikipedia.org/wiki/Empanada' ],
  Locro: [ 'locro.jpg', 'wikipedia.org/wiki/Locro' ],
  Zabaione: [ 'zabaione.jpg', 'wikipedia.org/wiki/Zabaione' ],
  Sorrentinos: [ 'sorrentinos.jpg', 'wikipedia.org/wiki/Sorrentinos' ],
  'Sandwiches De Miga': [ 'sandwiches_de_miga.jpg', 'wikipedia.org/wiki/Sandwiches_de_miga' ],
  Lasagna: [ 'lasagna.jpg', 'wikipedia.org/wiki/Lasagna' ],
  Moussaka: [ 'moussaka.jpg', 'wikipedia.org/wiki/Moussaka' ],
  'Tave Kosi': [ 'tave_kosi.jpg', 'wikipedia.org/wiki/Tavë_kosi' ],
  Waterzooi: [ 'waterzooi.jpg', 'wikipedia.org/wiki/Waterzooi' ],
  'Chocolate Mousse': [ 'chocolate_mousse.jpg', 'wikipedia.org/wiki/Mousse' ],
  'Ema Datshi': [ 'ema_datshi.jpg', 'wikipedia.org/wiki/Ema_datshi' ],
  Feijoada: [ 'feijoada.jpg', 'wikipedia.org/wiki/Feijoada' ],
  Ambuyat: [ 'ambuyat.jpg', 'wikipedia.org/wiki/Ambuyat' ],
  'Shopska Salad': [ 'shopska_salad.jpg', 'wikipedia.org/wiki/Shopska_salad' ],
  'Fish Amok': [ 'fish_amok.jpg', 'wikipedia.org/wiki/Fish_amok' ],
  'Num Banhchok': [ 'num_banhchok.jpg', 'wikipedia.org/wiki/Num_banhchok' ],
  'Samlar Kako': [ 'samlar_kako.jpg', 'wikipedia.org/wiki/Samlar_kako' ],
  Poutine: [ 'poutine.jpg', 'wikipedia.org/wiki/Poutine' ],
  'Butter Tart': [ 'butter_tart.jpg', 'wikipedia.org/wiki/Butter_tart' ],
  'Pastel De Choclo': [ 'pastel_de_choclo.jpg', 'wikipedia.org/wiki/Pastel_de_choclo' ],
  'Stegt Flaesk': [ 'stegt_flaesk.jpg', 'wikipedia.org/wiki/Stegt_flæsk' ],
  Encebollado: [ 'encebollado.jpg', 'wikipedia.org/wiki/Encebollado' ],
  Guatitas: [ 'guatitas.jfif', 'wikipedia.org/wiki/Guatitas' ],
  Lohikeitto: [ 'lohikeitto.jpg', 'wikipedia.org/wiki/Lohikeitto' ],
  'Beef Bourguignon': [ 'beef_bourguignon.jpg', 'wikipedia.org/wiki/Beef_bourguignon' ],
  'Blanquette De Veau': [ 'blanquette_de_veau.jpg', 'wikipedia.org/wiki/Blanquette_de_veau' ],
  'Steak Frites': [ 'steak_frites.jpg', 'wikipedia.org/wiki/Steak_frites' ]
}
